name: "use-case-2"
services:

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_DATABASE: crypto_db
      MYSQL_USER: stefan
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: unless-stopped

  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - '8080:8080'
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/crypto_db
        SPRING_DATASOURCE_USERNAME: stefan
        SPRING_DATASOURCE_PASSWORD: password
        SPRING_JPA_HIBERNATE_DDL_AUTO: update
      depends_on:
        - db
      restart: unless-stopped

  frontend:
    build:
      context: ./frontend/crypto-dashboard-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    restart: unless-stopped
       
volumes:
  db-data:
